# Generated by Django 4.0 on 2021-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_contains_in_comment_attached_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='contains_in',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, to='main.Card'),
        ),
    ]
