# Generated by Django 4.0 on 2021-12-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_card_contains_in_remove_deck_cards_deck_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.deck'),
        ),
    ]
